### ISSUE TITLE
Changing pre-padding to post-padding

### ISSUE THREAD

**Issue by pinesnow72** [kensho-technologies/bubs#19]
The flair embedding result is pre-padded, but I want to get post-padded embedding.
Is it possible to change pre-padding to post-padding with modifying InputEncoder?
Actually, I modified _prepare_index_array() and _prepare_mask_array() in InputEncoder class and could get post-padded embedding result, but I am not sure whether this result is actually reasonable or not when I use it in downstream task.

Below is the code I've modified.
I added self.prepad (bool) and selectively padded according to this value.

```
    def _prepare_index_array(self, index_list):
        """Make a 2D array where each row is a padded array of character-level token-end indices."""
        pad_len = self.max_token_sequence_len
        batch_size = len(index_list)
        padding_index = 0
        padded_sentences = np.full((batch_size, pad_len, 2), padding_index, dtype=np.int32)
        for i in range(batch_size):
            clipped_len = min(len(index_list[i]), pad_len)
            padded_sentences[i, :, 0] = i
            if self.prepad:
                padded_sentences[i, pad_len - clipped_len:, 1] = index_list[i][:clipped_len]
            else:
                padded_sentences[i, :clipped_len, 1] = index_list[i][:clipped_len]
        return padded_sentences

    def _prepare_mask_array(self, index_list):
        """Make 2D array where each row contains 1's where real tokens were and 0's where padded."""
        pad_len = self.max_token_sequence_len
        batch_size = len(index_list)
        mask = np.zeros((batch_size, pad_len))
        for i, inds in enumerate(index_list):
            if self.prepad:
                mask[i, pad_len - len(inds):] = 1
            else:
                mask[i, :len(inds)] = 1
        return mask

```

**Comment by ydovzhenko** [comment]
I actually thought about implementing both ways, but there was no particular use case for that at the time and I just stuck to my existing convention. 

Your code above looks like it should work great though!

**Comment by pinesnow72** [comment]
> I actually thought about implementing both ways, but there was no particular use case for that at the time and I just stuck to my existing convention.
> 
> Your code above looks like it should work great though!

Thank you for your reply and sharing this repository.
